### ISSUE TITLE
Add CSS/SCSS file processor

### ISSUE THREAD

**Issue by dezhidki** [JYU-DI/timsync#14]
Add a file processor for style files. 

The style files can define a front matter via `/*` and `*/` as such:

```css
/*
foo: blue
bar: 2
*/

p {
  color: {{foo}};
}
```
