### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by dezhidki** [JYU-DI/timsync#7]
Add a GitHub action to set up timsync and sync the repo with a specific target

**Comment by dezhidki** [comment]
Done in 7285002484a057110f1c6c4c8166c7ad38bf501d

Basic workflow with the example action:

```yml
name: Run

on: push

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: JYU-DI/timsync@main
              with:
                host: https://tim.jyu.fi
                folder_root: ${{ secrets.TIM_FOLDER_ROOT }}
                username: ${{ secrets.TIM_USERNAME }}
                password: ${{ secrets.TIM_PASSWORD }}
```
